// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChn1UUDdKP8UNDMNRsApCngJZNoqJdF1s',
    appId: '1:486202489831:web:e78df118034ecd01405b42',
    messagingSenderId: '486202489831',
    projectId: 'smart-trolley-d480f',
    authDomain: 'smart-trolley-d480f.firebaseapp.com',
    databaseURL: 'https://smart-trolley-d480f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-d480f.firebasestorage.app',
    measurementId: 'G-JNGXHDL04Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1GKg1H-ZSrVuU4FTPlyloCG_6d_MKWE',
    appId: '1:486202489831:android:dc7a36935503e9d2405b42',
    messagingSenderId: '486202489831',
    projectId: 'smart-trolley-d480f',
    databaseURL: 'https://smart-trolley-d480f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-d480f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEWH__rUZhFBOCPyy7yS5NBXB21KoUnAM',
    appId: '1:486202489831:ios:558a11ed1e6f5227405b42',
    messagingSenderId: '486202489831',
    projectId: 'smart-trolley-d480f',
    databaseURL: 'https://smart-trolley-d480f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-d480f.firebasestorage.app',
    iosBundleId: 'com.example.smartTrolley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEWH__rUZhFBOCPyy7yS5NBXB21KoUnAM',
    appId: '1:486202489831:ios:558a11ed1e6f5227405b42',
    messagingSenderId: '486202489831',
    projectId: 'smart-trolley-d480f',
    databaseURL: 'https://smart-trolley-d480f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-d480f.firebasestorage.app',
    iosBundleId: 'com.example.smartTrolley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChn1UUDdKP8UNDMNRsApCngJZNoqJdF1s',
    appId: '1:486202489831:web:9c42d7b027ef7e63405b42',
    messagingSenderId: '486202489831',
    projectId: 'smart-trolley-d480f',
    authDomain: 'smart-trolley-d480f.firebaseapp.com',
    databaseURL: 'https://smart-trolley-d480f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trolley-d480f.firebasestorage.app',
    measurementId: 'G-HJ377QRV4N',
  );
}
